version: '3.8'

services:
  clothai:
    build: .
    container_name: clothai
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - sqlite_data:/app/data
    environment:
      - SQLITE_DB_PATH=/app/data/clothai.db

volumes:
  sqlite_data:
    name: clothai_sqlite_data
