name: Deploy to Server

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create .env file
      run: |
        echo "EACHLABS_API_KEY=${{ secrets.EACHLABS_API_KEY }}" > .env
        echo "IMGBB_API_KEY=${{ secrets.IMGBB_API_KEY }}" >> .env
      
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: 162.55.51.97
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          echo "Starting deployment..."
          
          # Create app directory if it doesn't exist
          mkdir -p ~/clothai
          cd ~/clothai
          
          # Stop existing service if running
          if [ -f ~/clothai/main.pid ]; then
            echo "Stopping existing service..."
            kill $(cat ~/clothai/main.pid) || true
            rm ~/clothai/main.pid
          fi
          
          # Clean old files
          echo "Cleaning old files..."
          rm -rf ~/clothai/*
          
          # Create temporary directory for files
          echo "Creating temporary directory..."
          mkdir -p ~/temp_deploy
          cd ~/temp_deploy
          
          # Download repository files
          echo "Downloading repository..."
          git clone https://github.com/${{ github.repository }}.git .
          
          # Copy all files to app directory
          echo "Copying files to app directory..."
          cp -r * ~/clothai/
          cp .env ~/clothai/
          
          # Clean up temp directory
          cd ~
          rm -rf ~/temp_deploy
          
          # Set up Python virtual environment
          echo "Setting up Python environment..."
          cd ~/clothai
          python3 -m venv venv
          source venv/bin/activate
          
          # Install dependencies
          echo "Installing dependencies..."
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
          
          # Create .env file
          echo "Creating .env file..."
          echo "EACHLABS_API_KEY=${{ secrets.EACHLABS_API_KEY }}" > .env
          echo "IMGBB_API_KEY=${{ secrets.IMGBB_API_KEY }}" >> .env
          
          # Start the service
          echo "Starting the service..."
          cd ~/clothai
          source venv/bin/activate
          nohup python3 -m uvicorn main:app --host 0.0.0.0 --port 8000 --workers 4 > app.log 2>&1 & echo $! > main.pid
          
          # Verify service is running
          echo "Verifying service..."
          sleep 5
          if ps -p $(cat main.pid) > /dev/null; then
            echo "Service is running with PID $(cat main.pid)"
          else
            echo "Service failed to start"
            cat app.log
            exit 1
          fi
          
          # Test the endpoint
          echo "Testing endpoint..."
          curl -f http://localhost:8000/docs || exit 1
          
          echo "Deployment completed successfully!"
